# Wayland
WAYLAND_DISPLAY=wayland-1
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_DESKTOP=sway

# GTK
GTK_THEME=adw-gtk3-dark
XCURSOR_THEME=Adwaita
XCURSOR_SIZE=24
# Force GTK4 apps to use Wayland backend
GDK_BACKEND=wayland,x11

# Qt (Wayland-native with X11 fallback)
QT_QPA_PLATFORM=wayland;xcb
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_AUTO_SCREEN_SCALE_FACTOR=1

# Firefox / Thunderbird Wayland
MOZ_ENABLE_WAYLAND=1

# SSH askpass
SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass
SSH_ASKPASS_REQUIRE=prefer

# Clutter
CLUTTER_BACKEND=wayland

# SDL
SDL_VIDEODRIVER=wayland
